name: Build GitHub Pages

on:
    push:
        branches:
            - main
            #- cur_ver_release
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build-github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Install Hugo
              run: sudo snap install hugo
            - name: Checkout Repo
              uses: actions/checkout@v7
            - name: Build Pages
              run: make
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: exampleSite/public
    deploy:
        runs-on: ubuntu-latest
        needs: build-github-pages
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v5
